services:

  db:
    image: postgres
    container_name: regular_script_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: QAZ78963wsx
      POSTGRES_USER: postgresuser
      POSTGRES_DB: regular_script
      PGDATA: ~/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "1713:5432"